// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DashboardState {
    /**
     * Creates a new DashboardState instance.
     * @param {Partial<DashboardState>} [$$source = {}] - The source object to create the DashboardState.
     */
    constructor($$source = {}) {
        if (!("surveyTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surveyTitle"] = "";
        }
        if (!("surveyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["surveyUrl"] = "";
        }
        if (!("targetCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetCount"] = 0;
        }
        if (!("threadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threadCount"] = 0;
        }
        if (!("randomIpEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["randomIpEnabled"] = false;
        }
        if (!("randomIpQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["randomIpQuota"] = 0;
        }
        if (!("randomIpQuotaLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["randomIpQuotaLabel"] = "";
        }
        if (!("randomIpStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["randomIpStatus"] = "";
        }
        if (!("randomIpStatusTone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["randomIpStatusTone"] = "";
        }
        if (!("proxySource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxySource"] = "";
        }
        if (!("questionCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["questionCount"] = 0;
        }
        if (!("progressCurrent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressCurrent"] = 0;
        }
        if (!("progressTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressTarget"] = 0;
        }
        if (!("progressPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progressPercent"] = 0;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("platformLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platformLabel"] = "";
        }
        if (!("metrics" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["metrics"] = [];
        }
        if (!("quickActions" in $$source)) {
            /**
             * @member
             * @type {QuickAction[]}
             */
            this["quickActions"] = [];
        }
        if (!("questionRows" in $$source)) {
            /**
             * @member
             * @type {QuestionRow[]}
             */
            this["questionRows"] = [];
        }
        if (!("sessionRows" in $$source)) {
            /**
             * @member
             * @type {SessionRow[]}
             */
            this["sessionRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DashboardState}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType1;
        const $$createField17_0 = $$createType3;
        const $$createField18_0 = $$createType5;
        const $$createField19_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField16_0($$parsedSource["metrics"]);
        }
        if ("quickActions" in $$parsedSource) {
            $$parsedSource["quickActions"] = $$createField17_0($$parsedSource["quickActions"]);
        }
        if ("questionRows" in $$parsedSource) {
            $$parsedSource["questionRows"] = $$createField18_0($$parsedSource["questionRows"]);
        }
        if ("sessionRows" in $$parsedSource) {
            $$parsedSource["sessionRows"] = $$createField19_0($$parsedSource["sessionRows"]);
        }
        return new DashboardState(/** @type {Partial<DashboardState>} */($$parsedSource));
    }
}

export class NavItem {
    /**
     * Creates a new NavItem instance.
     * @param {Partial<NavItem>} [$$source = {}] - The source object to create the NavItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("section" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["section"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["badge"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["selected"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NavItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NavItem(/** @type {Partial<NavItem>} */($$parsedSource));
    }
}

export class PageMetric {
    /**
     * Creates a new PageMetric instance.
     * @param {Partial<PageMetric>} [$$source = {}] - The source object to create the PageMetric.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tone"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageMetric instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageMetric}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageMetric(/** @type {Partial<PageMetric>} */($$parsedSource));
    }
}

export class QuestionRow {
    /**
     * Creates a new QuestionRow instance.
     * @param {Partial<QuestionRow>} [$$source = {}] - The source object to create the QuestionRow.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("dimension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dimension"] = "";
        }
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuestionRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionRow(/** @type {Partial<QuestionRow>} */($$parsedSource));
    }
}

export class QuickAction {
    /**
     * Creates a new QuickAction instance.
     * @param {Partial<QuickAction>} [$$source = {}] - The source object to create the QuickAction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["emphasis"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuickAction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickAction(/** @type {Partial<QuickAction>} */($$parsedSource));
    }
}

export class ReverseFillRow {
    /**
     * Creates a new ReverseFillRow instance.
     * @param {Partial<ReverseFillRow>} [$$source = {}] - The source object to create the ReverseFillRow.
     */
    constructor($$source = {}) {
        if (!("question" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["question"] = "";
        }
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReverseFillRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReverseFillRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReverseFillRow(/** @type {Partial<ReverseFillRow>} */($$parsedSource));
    }
}

export class SessionRow {
    /**
     * Creates a new SessionRow instance.
     * @param {Partial<SessionRow>} [$$source = {}] - The source object to create the SessionRow.
     */
    constructor($$source = {}) {
        if (!("thread" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thread"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRow(/** @type {Partial<SessionRow>} */($$parsedSource));
    }
}

export class SettingField {
    /**
     * Creates a new SettingField instance.
     * @param {Partial<SettingField>} [$$source = {}] - The source object to create the SettingField.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingField}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new SettingField(/** @type {Partial<SettingField>} */($$parsedSource));
    }
}

export class SettingsGroup {
    /**
     * Creates a new SettingsGroup instance.
     * @param {Partial<SettingsGroup>} [$$source = {}] - The source object to create the SettingsGroup.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {SettingField[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new SettingsGroup(/** @type {Partial<SettingsGroup>} */($$parsedSource));
    }
}

export class ShellState {
    /**
     * Creates a new ShellState instance.
     * @param {Partial<ShellState>} [$$source = {}] - The source object to create the ShellState.
     */
    constructor($$source = {}) {
        if (!("appTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appTitle"] = "";
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("themeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeMode"] = "";
        }
        if (!("currentPage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentPage"] = "";
        }
        if (!("topNav" in $$source)) {
            /**
             * @member
             * @type {NavItem[]}
             */
            this["topNav"] = [];
        }
        if (!("bottomNav" in $$source)) {
            /**
             * @member
             * @type {NavItem[]}
             */
            this["bottomNav"] = [];
        }
        if (!("dashboard" in $$source)) {
            /**
             * @member
             * @type {DashboardState}
             */
            this["dashboard"] = (new DashboardState());
        }
        if (!("runtimeGroups" in $$source)) {
            /**
             * @member
             * @type {SettingsGroup[]}
             */
            this["runtimeGroups"] = [];
        }
        if (!("strategyRules" in $$source)) {
            /**
             * @member
             * @type {StrategyRule[]}
             */
            this["strategyRules"] = [];
        }
        if (!("dimensionGroups" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dimensionGroups"] = [];
        }
        if (!("reverseFillPlan" in $$source)) {
            /**
             * @member
             * @type {ReverseFillRow[]}
             */
            this["reverseFillPlan"] = [];
        }
        if (!("logLines" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logLines"] = [];
        }
        if (!("communityItems" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["communityItems"] = [];
        }
        if (!("aboutItems" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["aboutItems"] = [];
        }
        if (!("donateItems" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["donateItems"] = [];
        }
        if (!("ipUsageItems" in $$source)) {
            /**
             * @member
             * @type {PageMetric[]}
             */
            this["ipUsageItems"] = [];
        }
        if (!("settingsGroups" in $$source)) {
            /**
             * @member
             * @type {SettingsGroup[]}
             */
            this["settingsGroups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShellState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType15;
        const $$createField8_0 = $$createType17;
        const $$createField9_0 = $$createType8;
        const $$createField10_0 = $$createType19;
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType8;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topNav" in $$parsedSource) {
            $$parsedSource["topNav"] = $$createField4_0($$parsedSource["topNav"]);
        }
        if ("bottomNav" in $$parsedSource) {
            $$parsedSource["bottomNav"] = $$createField5_0($$parsedSource["bottomNav"]);
        }
        if ("dashboard" in $$parsedSource) {
            $$parsedSource["dashboard"] = $$createField6_0($$parsedSource["dashboard"]);
        }
        if ("runtimeGroups" in $$parsedSource) {
            $$parsedSource["runtimeGroups"] = $$createField7_0($$parsedSource["runtimeGroups"]);
        }
        if ("strategyRules" in $$parsedSource) {
            $$parsedSource["strategyRules"] = $$createField8_0($$parsedSource["strategyRules"]);
        }
        if ("dimensionGroups" in $$parsedSource) {
            $$parsedSource["dimensionGroups"] = $$createField9_0($$parsedSource["dimensionGroups"]);
        }
        if ("reverseFillPlan" in $$parsedSource) {
            $$parsedSource["reverseFillPlan"] = $$createField10_0($$parsedSource["reverseFillPlan"]);
        }
        if ("logLines" in $$parsedSource) {
            $$parsedSource["logLines"] = $$createField11_0($$parsedSource["logLines"]);
        }
        if ("communityItems" in $$parsedSource) {
            $$parsedSource["communityItems"] = $$createField12_0($$parsedSource["communityItems"]);
        }
        if ("aboutItems" in $$parsedSource) {
            $$parsedSource["aboutItems"] = $$createField13_0($$parsedSource["aboutItems"]);
        }
        if ("donateItems" in $$parsedSource) {
            $$parsedSource["donateItems"] = $$createField14_0($$parsedSource["donateItems"]);
        }
        if ("ipUsageItems" in $$parsedSource) {
            $$parsedSource["ipUsageItems"] = $$createField15_0($$parsedSource["ipUsageItems"]);
        }
        if ("settingsGroups" in $$parsedSource) {
            $$parsedSource["settingsGroups"] = $$createField16_0($$parsedSource["settingsGroups"]);
        }
        return new ShellState(/** @type {Partial<ShellState>} */($$parsedSource));
    }
}

export class StrategyRule {
    /**
     * Creates a new StrategyRule instance.
     * @param {Partial<StrategyRule>} [$$source = {}] - The source object to create the StrategyRule.
     */
    constructor($$source = {}) {
        if (!("condition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["condition"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StrategyRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StrategyRule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StrategyRule(/** @type {Partial<StrategyRule>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PageMetric.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = QuickAction.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = QuestionRow.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SessionRow.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = SettingField.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = NavItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = DashboardState.createFrom;
const $$createType14 = SettingsGroup.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = StrategyRule.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ReverseFillRow.createFrom;
const $$createType19 = $Create.Array($$createType18);
