// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DashboardState {
    "surveyTitle": string;
    "surveyUrl": string;
    "targetCount": number;
    "threadCount": number;
    "randomIpEnabled": boolean;
    "randomIpQuota": number;
    "randomIpQuotaLabel": string;
    "randomIpStatus": string;
    "randomIpStatusTone": string;
    "proxySource": string;
    "questionCount": number;
    "progressCurrent": number;
    "progressTarget": number;
    "progressPercent": number;
    "statusText": string;
    "platformLabel": string;
    "metrics": PageMetric[] | null;
    "quickActions": QuickAction[] | null;
    "questionRows": QuestionRow[] | null;
    "sessionRows": SessionRow[] | null;
}

export interface NavItem {
    "id": string;
    "label": string;
    "icon": string;
    "section": string;
    "badge"?: string;
    "selected"?: boolean;
}

export interface PageMetric {
    "label": string;
    "value": string;
    "tone"?: string;
}

export interface QuestionRow {
    "index": number;
    "type": string;
    "dimension": string;
    "strategy": string;
}

export interface QuickAction {
    "id": string;
    "label": string;
    "icon": string;
    "emphasis"?: string;
}

export interface ReverseFillRow {
    "question": string;
    "column": string;
    "state": string;
}

export interface SessionRow {
    "thread": string;
    "status": string;
    "progress": number;
}

export interface SettingField {
    "id": string;
    "label": string;
    "description": string;
    "kind": string;
    "value": string;
    "options"?: string[] | null;
}

export interface SettingsGroup {
    "title": string;
    "fields": SettingField[] | null;
}

export interface ShellState {
    "appTitle": string;
    "appVersion": string;
    "themeMode": string;
    "currentPage": string;
    "topNav": NavItem[] | null;
    "bottomNav": NavItem[] | null;
    "dashboard": DashboardState;
    "runtimeGroups": SettingsGroup[] | null;
    "strategyRules": StrategyRule[] | null;
    "dimensionGroups": string[] | null;
    "reverseFillPlan": ReverseFillRow[] | null;
    "logLines": string[] | null;
    "communityItems": string[] | null;
    "aboutItems": PageMetric[] | null;
    "donateItems": PageMetric[] | null;
    "ipUsageItems": PageMetric[] | null;
    "settingsGroups": SettingsGroup[] | null;
}

export interface StrategyRule {
    "condition": string;
    "action": string;
    "target": string;
}
