import type { ShellState } from '../types'

export const mockShellState: ShellState = {
  appTitle: 'SurveyController',
  appVersion: '0.1.0-alpha',
  themeMode: 'system',
  currentPage: 'dashboard',
  topNav: [
    { id: 'dashboard', label: '概览', icon: 'home', section: 'top', selected: true },
    { id: 'runtime', label: '运行参数', icon: 'settings', section: 'top' },
    { id: 'strategy', label: '题目策略', icon: 'flow', section: 'top' },
    { id: 'reverse-fill', label: '反填', icon: 'refresh', section: 'top', badge: '预览' },
    { id: 'logs', label: '日志', icon: 'document', section: 'top' },
  ],
  bottomNav: [
    { id: 'community', label: '社区', icon: 'chat', section: 'bottom' },
    { id: 'settings', label: '设置', icon: 'sliders', section: 'bottom' },
    { id: 'more', label: '更多', icon: 'grid', section: 'bottom' },
  ],
  dashboard: {
    surveyTitle: '大学生消费观问卷',
    surveyUrl: '',
    targetCount: 1,
    threadCount: 1,
    randomIpEnabled: false,
    randomIpQuota: 97,
    randomIpQuotaLabel: '10241/10530',
    randomIpStatus: '服务正常',
    randomIpStatusTone: 'success',
    proxySource: '默认',
    proxyAvailable: 0,
    proxyInUse: 0,
    questionCount: 0,
    progressCurrent: 0,
    progressTarget: 1,
    progressPercent: 0,
    statusText: '等待配置',
    platformLabel: '问卷星',
    metrics: [],
    quickActions: [],
    questionRows: [],
    sessionRows: [],
  },
  runtimeGroups: [],
  strategyRules: [],
  dimensionGroups: [],
  reverseFillPlan: [],
  logLines: [],
  communityItems: [],
  aboutItems: [],
  donateItems: [],
  ipUsageItems: [],
  settingsGroups: [],
}
